#!/bin/bash

echo "=========================================="
echo " 语音识别系统 - 前后端分离版本"
echo "=========================================="
echo ""

# 检查Python环境
echo "🔍 检查Python环境..."
python3 --version
echo ""

# 检查依赖
echo " 检查依赖包..."
pip3 list | grep -E "streamlit|fastapi|requests"
echo ""

echo "=========================================="
echo " 启动指南"
echo "=========================================="
echo ""
echo "1️⃣  启动后端服务（终端1）:"
echo "   python api.py"
echo "   或"
echo "   uvicorn api:app --host 0.0.0.0 --port 8000 --reload"
echo ""
echo "   🌐 API地址: http://localhost:8000"
echo "   📖 API文档: http://localhost:8000/docs"
echo ""
echo "2️  启动前端服务（终端2）:"
echo "   streamlit run app.py"
echo ""
echo "   🌐 Web UI: http://localhost:8501"
echo ""
echo "=========================================="
echo " 功能测试"
echo "=========================================="
echo ""
echo "✅ 登录持久化测试:"
echo "   1. 访问 http://localhost:8501"
echo "   2. 输入用户名密码登录"
echo "   3. 登录成功后按F5刷新"
echo "   4. 预期: 保持登录状态 ✅"
echo ""
echo "✅ 任务列表测试:"
echo "   1. 查看仪表盘任务列表"
echo "   2. 预期: 正常显示任务 ✅"
echo ""
echo "✅ 硬件信息测试:"
echo "   1. 查看侧边栏硬件信息"
echo "   2. 预期: 显示CPU/GPU信息 ✅"
echo ""
echo "=========================================="
echo " 文档列表"
echo "=========================================="
echo ""
echo "📄 架构方案: ARCHITECTURE_REFACTORING_PLAN.md (526行)"
echo "📄 实施进度: FRONTEND_BACKEND_SEPARATION_PROGRESS.md (454行)"
echo "📄 实施总结: IMPLEMENTATION_SUMMARY.md (572行)"
echo " 溢出修复: TASK_LIST_OVERFLOW_FIX.md (353行)"
echo "📄 API客户端: api_client.py (250行)"
echo ""
echo "=========================================="
echo " 改造进度"
echo "=========================================="
echo ""
echo "✅ 已完成:"
echo "   - localStorage登录持久化"
echo "   - API客户端封装"
echo "   - 认证API"
echo "   - 硬件信息API调用"
echo "   - 任务列表API调用"
echo ""
echo " 待改造:"
echo "   - 任务详情查询"
echo "   - 单个音频分析"
echo "   - 批量处理"
echo "   - 报表生成"
echo "   - 系统配置"
echo ""
echo "总体进度: 约30%（基础架构已完成）"
echo ""
echo "=========================================="
echo ""
echo "💡 提示: 详细的改造清单请查看 IMPLEMENTATION_SUMMARY.md"
echo ""
